### PR TITLE
Additional findclade methods

### LINKED ISSUE #34: can findclade be modified so that it also takes taxa numbers as arguments, not just symbol?

### PR DESCRIPTION
**Pull request by anikaluo**
modified `findclade` to also take Int as `taxlevel` argument
updated documentation and added examples
(Closes #34)

### CODE REVIEW

**Comment by anikaluo** [comment]
Ah! I totally forgot that I was supposed to write a plan for this under the Issue! But I hope what I did is okay?

**Comment by kescobo** [comment]
Can you add tests as well?

**Comment by kescobo** [comment]
I think also add a single-argument method, something like

```
findclade(t::AbastractString) = findclade(t, length(split(t, '|')))
```

**Comment by anikaluo** [comment]
1. Is the `jldoctest` section in the documentation not part of testing?
2. Just added a single argument method.

**Comment by kescobo** [comment]
doctests are good, but don't get counted in the coverage statistics. It's good to have both.

**Review by kescobo — APPROVED** [review]

**Pull request merged**
